services:
  - type: web
    name: chat
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: "dutrr6tj2"
      - key: CLOUDINARY_API_KEY
        value: "997227339798211"
      - key: CLOUDINARY_API_SECRET
        value: "_o6ZiZAk26UfjBKbJZkw3ynrQGs"
